name: Release
on:
  push:
    branches:
      - master

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    # needs: bump_version
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pin to IPFS
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.3
        with:
          pin-name: Hello
          path: './build'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}

      # - name: Pin to Crust
      #   uses: crustio/ipfs-crust-action@v2.0.4
      #   continue-on-error: true
      #   timeout-minutes: 2
      #   with:
      #     cid: ${{ steps.upload.outputs.hash }}
      #     seeds: ${{ secrets.CRUST_SEEDS }}


      - name: Convert CIDv0 to CIDv1
        id: convert_cidv0
        uses: uniswap/convert-cidv0-cidv1@v1.0.0
        with:
          cidv0: ${{ steps.upload.outputs.hash }}

      - name: Update DNS with new IPFS hash
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: 'uniswap.org'
          RECORD_NAME: '_dnslink.app'
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        uses: textileio/cloudflare-update-dnslink@0fe7b7a1ffc865db3a4da9773f0f987447ad5848
        with:
          cid: ${{ steps.upload.outputs.hash }}