name: Release
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # bump_version:
  #   name: Bump Version
  #   runs-on: ubuntu-latest
  #   outputs:
  #     new_tag: ${{ steps.github_tag_action.outputs.new_tag }}
  #     changelog: ${{ steps.github_tag_action.outputs.changelog }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Bump version and push tag
  #       id: github_tag_action
  #       uses: mathieudutour/github-tag-action@331898d5052eedac9b15fec867b5ba66ebf9b692
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         release_branches: .*
  #         default_bump: false

  build:
    name: Create Release
    runs-on: ubuntu-latest
    # needs: bump_version
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Pin to IPFS
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.3
        with:
          pin-name: Hello
          path: './build'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}
          verbose: true
          remove-old: false
      # - name: Pin to Crust
      #   uses: crustio/ipfs-crust-action@v2.0.4
      #   continue-on-error: true
      #   timeout-minutes: 2
      #   with:
      #     cid: ${{ steps.upload.outputs.hash }}
      #     seeds: ${{ secrets.CRUST_SEEDS }}


      - name: Convert CIDv0 to CIDv1
        id: convert_cidv0
        uses: uniswap/convert-cidv0-cidv1@v1.0.0
        with:
          cidv0: ${{ steps.upload.outputs.hash }}

      # - name: Update DNS with new IPFS hash
      #   env:
      #     CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      #     RECORD_DOMAIN: '21r.com'
      #     RECORD_NAME: '_dnslink.app'
      #     CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      #   uses: textileio/cloudflare-update-dnslink@v2

      #   with:
      #     cid: ${{ steps.upload.outputs.hash }}

      - name: Update DNSLink
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: "21r.com"
          RECORD_NAME: "_dnslink.app"
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        id: dnslink_app
        uses: textileio/cloudflare-update-dnslink@master
        with:
          cid: ${{ steps.upload.outputs.hash }}

      - name: Update DNSLink
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: "21r.com"
          RECORD_NAME: "_dnslink"
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        id: dnslink
        uses: textileio/cloudflare-update-dnslink@master
        with:
          cid: ${{ steps.upload.outputs.hash }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Hello6.83
          release_name: Release Hello6.83
          body: |
            IPFS hash of the deployment:
            - CIDv0: `${{ steps.upload.outputs.hash }}`
            - CIDv1: `${{ steps.convert_cidv0.outputs.cidv1 }}`
            The latest release is always accessible via our alias to the Cloudflare IPFS gateway at [app.uniswap.org](https://app.uniswap.org).
            You can also access the Uniswap Interface directly from an IPFS gateway.
            **BEWARE**: The Uniswap interface uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to remember your settings, such as which tokens you have imported.
            **You should always use an IPFS gateway that enforces origin separation**, or our alias to the latest release at [app.uniswap.org](https://app.uniswap.org).
            Your Uniswap settings are never remembered across different URLs.
            IPFS gateways:
            - https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.dweb.link/
            - https://${{ steps.convert_cidv0.outputs.cidv1 }}.ipfs.cf-ipfs.com/
            - [ipfs://${{ steps.upload.outputs.hash }}/](ipfs://${{ steps.upload.outputs.hash }}/)
